server:
  port: 3344

spring:
  application:
    name: cloud-config-center  #注册 eureka 服务器的微服务名称
  cloud:
    config:
      server:
        git:
          uri:
          #搜索目录
          search-paths: aaa
      #读取分支
      label: master



eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
