server:
  port: 3344

spring:
  application:
    name: cloud-config-center  #注册 eureka 服务器的微服务名称
  cloud:
    config:
      server:
        git:
          uri: https://github.com/quxinjun1993/atguigu-springcloud.git
          #搜索目录
          search-paths:
            - cloud-config-center-3344
      #读取分支
      label: dev



eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
