server:
  port: 80

spring:
  application:
    name: cloud-order-service


eureka:
  client:
    #表示是否将自己注册进EurekaServer 默认true
    register-with-eureka: true
    #表示是否从EurekaServer抓取已有的注册信息，默认为true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
#      defaultZone: http://localhost:7001/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: CONSUMER-ORDER-80   #配置主机名称
    prefer-ip-address: true          #配置显示ip
    instance:
    #Eureka客户端向服务端发送心跳的时间间隔，单位为：秒（默认是30s）
    lease-renewal-interval-in-seconds: 60
    #Eureka服务端在收到最后一次心跳后等待时间上线，单位为秒（默认是90s），超市将剔除服务
    lease-expiration-duration-in-seconds: 120
